import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'
import { StoreProvider } from './redux/StoreProvider'
import { ThemeProvider } from 'next-themes'
import { LoadingProvider } from '@/context/LoadingContext'
import GlobalLoading from '@/components/GlobalLoading'
import RefreshToken from './auth/_component/RefreshToken'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata: Metadata = {
  title: 'PATO',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
            <LoadingProvider>
              <GlobalLoading />
              <Toaster />
              {/* <RefreshToken /> */}
              {children}
            </LoadingProvider>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
